api:
  aqi_url: ${API_URL}
  aqi_token: ${API_TOKEN}
  carbon_url: ${CARBON_API_URL}
  carbon_token: ${CARBON_API_TOKEN}

location:
  city_lat: ${CITY_LAT}
  city_lon: ${CITY_LON}

data_collection:
  request_interval: 30
  total_collection_time: 60

output:
  save_directory: ${SAVE_DIR}
  filename: "sakarya_data.json"

hopsworks:
  project_name: ${HW_PROJECT_NAME}
  feature_group_name: ${HW_FEATURE_GN}
  api_key: ${HOPSWORKS_API_KEY}